CREATE TABLE PUBLIC.profiles
(
  id BIGINT PRIMARY KEY IDENTITY,
  name VARCHAR(255) DEFAULT '',
  description VARCHAR(255) DEFAULT ''
);

CREATE TABLE PUBLIC.timings
(
  id BIGINT PRIMARY KEY IDENTITY,
  name VARCHAR(255) DEFAULT '',
);