CREATE TABLE profiles
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT '',
  description VARCHAR(255) DEFAULT ''
);

CREATE TABLE timing_configs
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT '',
  description VARCHAR(255) DEFAULT '',
  profile_id BIGINT NOT NULL
);

CREATE TABLE timings
(
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT '',
  unit VARCHAR(255) DEFAULT '',
  duration BIGINT DEFAULT 0,
  timing_config_id BIGINT NOT NULL
);